version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages
      - name: image_detections

models:
  - name: stg_telegram_messages
    description: "Cleaned telegram messages"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: message
        tests:
          - not_null
      - name: channel_id
        tests:
          - not_null

  - name: fct_messages
    description: "Fact table for message analytics"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: channel_id
        tests:
          - not_null
      - name: has_image
        tests:
          - accepted_values:
              values: [true, false]
