version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages

models:
  - name: stg_telegram_messages
    description: "Flattened staging model from raw JSON"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: channel_id
        tests:
          - not_null
      - name: sent_at
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension table"

  - name: dim_channels
    description: "Channel dimension table"

  - name: fct_messages
    description: "Fact table of all telegram messages"
    columns:
      - name: id
        tests:
          - unique
          - not_null

